/**
 * Creating a sidebar enables you to:
 *
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined
 * here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  testing: [{ type: 'autogenerated', dirName: 'testing' },],
  inventory: [{ type: 'autogenerated', dirName: 'inventory' },],
  platform: [{ type: 'autogenerated', dirName: 'platform' },],
};

module.exports = sidebars;
