/**
 * Creating a sidebar enables you to:
 *
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined
 * here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  inventory: [{ type: "autogenerated", dirName: "01-inventory" }],
  api_dast: [{ type: "autogenerated", dirName: "02-api-dast" }],
  platform: [{ type: "autogenerated", dirName: "03-platform" }],
  frontend_dast: [{ type: "autogenerated", dirName: "04-frontend-dast" }],
};

module.exports = sidebars;
